PROJECT_NAME = 'Example'
TEST_TARGET = 'ExampleTests'
SCHEME_FILE = 'ExampleTests.xcscheme'

xcodeproj 'Example'
target 'ExampleTests', :exclusive => true do
  pod 'EarlGrey'
end

post_install do |installer|
  load('configure_earlgrey_pods.rb')
  configure_for_earlgrey(installer, PROJECT_NAME, TEST_TARGET, SCHEME_FILE)
end
